#pragma once
#include "FBCommonHeaders/Types.h"

DECLARE_SMART_PTR(ID3D11Device);
DECLARE_SMART_PTR(IDXGIFactory1);
DECLARE_SMART_PTR(IDXGISwapChain);
DECLARE_SMART_PTR(ID3DX11ThreadPump);
DECLARE_SMART_PTR(ID3D11DeviceContext);
DECLARE_SMART_PTR(IDXGIOutput);
DECLARE_SMART_PTR(IDXGIAdapter1);

DECLARE_SMART_PTR(ID3D11Buffer);
DECLARE_SMART_PTR(ID3D11Texture2D);
DECLARE_SMART_PTR(ID3D11ShaderResourceView);
DECLARE_SMART_PTR(ID3D11RenderTargetView);
DECLARE_SMART_PTR(ID3D11DepthStencilView);

DECLARE_SMART_PTR(ID3D11InputLayout);

DECLARE_SMART_PTR(ID3D11VertexShader);
DECLARE_SMART_PTR(ID3D11HullShader);
DECLARE_SMART_PTR(ID3D11DomainShader);
DECLARE_SMART_PTR(ID3D11GeometryShader);
DECLARE_SMART_PTR(ID3D11PixelShader);

DECLARE_SMART_PTR(ID3D11RasterizerState);
DECLARE_SMART_PTR(ID3D11BlendState);
DECLARE_SMART_PTR(ID3D11DepthStencilState);
DECLARE_SMART_PTR(ID3D11SamplerState);